//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.TimeSpan> check_in_time { get; set; }
        public Nullable<System.TimeSpan> check_out_time { get; set; }
        public Nullable<int> overtime_hours { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> employee_id { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
