//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public Nullable<bool> gender { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string avatar { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> contract_Id { get; set; }
    
        public virtual contract contract { get; set; }
        public virtual department department { get; set; }
        public virtual position position { get; set; }
        public virtual user user { get; set; }
    }
}
