//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonManager.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int id { get; set; }
        public Nullable<decimal> basicSalary { get; set; }
        public Nullable<decimal> allowance { get; set; }
        public Nullable<int> coefficient { get; set; }
        public Nullable<decimal> hourlyRate { get; set; }
        public Nullable<int> employee_id { get; set; }
        [JsonIgnore]    
        public virtual employee employee { get; set; }
    }
}
